# path to your genome (fasta format)
genome: "data/candidatus_methanomethylophilus_alvus_Mx1201.fasta"

# output directory
output_dir: "results/candidatus_methanomethylophilus_alvus_Mx1201"

# name of the reference database
ref_database: "uniref90"

# URL of the reference database
ref_database_url: "ftp.uniprot.org/pub/databases/uniprot/uniref/uniref90/uniref90.fasta.gz"

# directory containing various data
data_dir: "data"

# maximum number of thread to use
max_threads: 12
