genome: "data/candidatus_methanomethylophilus_alvus_Mx1201.fasta"
output_dir: "results/candidatus_methanomethylophilus_alvus_Mx1201"
ref_database: "uniref90"
ref_database_url: "ftp.uniprot.org/pub/databases/uniprot/uniref/uniref90/uniref90.fasta.gz"
data_dir: "data"