genome: "data/MalvusMx1201_GENOME_FASTA.fsa"
output_dir: "results/MalvusMx1201"
ref_database: "uniref90"
ref_database_url: "ftp.uniprot.org/pub/databases/uniprot/uniref/uniref90/uniref90.fasta.gz"
data_dir: "data"