name: PylProtPredictor
channels:
- bioconda
- r
- defaults
- conda-forge
dependencies:
- biopython=1.69=np110py35_0
- diamond=0.8.36=0
- dropbox=5.2.1=py35_0
- filechunkio=1.6=py35_0
- ftputil=3.2=py35_0
- mmtf-python=1.0.5=py35_0
- prodigal=2.6.3=0
- pycodestyle=2.0.0=py35_0
- pysftp=0.2.9=py35_0
- snakemake=3.11.2=py35_0
- urllib3=1.12=py35_0
- cffi=1.9.1=py35_0
- cryptography=1.7.1=py35_0
- docutils=0.13.1=py35_0
- flake8=3.3.0=py35_0
- freetype=2.5.5=2
- idna=2.2=py35_0
- jbig=2.1=0
- jpeg=9b=0
- libffi=3.2.1=1
- libgcc=4.8.5=1
- libpng=1.6.27=0
- libtiff=4.0.6=3
- mccabe=0.6.1=py35_0
- mkl=11.3.3=0
- msgpack-python=0.4.8=py35_0
- numpy=1.10.4=py35_2
- olefile=0.44=py35_0
- openssl=1.0.2k=1
- paramiko=2.1.2=py35_0
- pillow=4.1.0=py35_0
- pip=9.0.1=py35_1
- pyasn1=0.2.3=py35_0
- pycparser=2.17=py35_0
- pyflakes=1.5.0=py35_0
- python=3.5.3=1
- pyyaml=3.12=py35_0
- readline=6.2=2
- reportlab=3.4.0=py35_0
- requests=2.13.0=py35_0
- setuptools=27.2.0=py35_0
- six=1.10.0=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- wrapt=1.10.10=py35_0
- xz=5.2.2=1
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - pandas==0.19.2
  - python-dateutil==2.6.0
  - pytz==2017.2
