version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    environment:
      - MINICONDA: "$HOME/miniconda"
    steps:
      - checkout
      - run: echo 'export PATH=$HOME/miniconda3/bin:$PATH' >> $BASH_ENV
      - run:
          name: install miniconda
          command: |
            make install-conda
      - run:
          name: configure conda
          command: |
            make configure-conda
      - run:
          name: create conda environment
          command: |
            make create-env
      - run:
          name: run linting and test
          command: |
            source activate PylProtPredictor
            make test
      - run:
          name: update code coverage
          command: |
            source activate PylProtPredictor
            make coverage
